name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 1.3.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  responsive_framework:
#    path: ../
  # Uncomment to build standalone project.
  responsive_framework: ^0.2.0
  google_fonts: ^2.3.2
  animations: ^2.0.2
  loading_gifs: ^0.3.0
  # advance_pdf_viewer: any
  pdfx: ^2.2.0
  http: any
  syncfusion_flutter_pdfviewer: ^20.2.49-beta
  async: ^2.8.2
  syncfusion_flutter_core: ^20.2.49
  syncfusion_flutter_pdf: ^20.2.49
  syncfusion_pdfviewer_macos: ^20.2.49-beta
  syncfusion_pdfviewer_platform_interface: ^20.2.49-beta
  syncfusion_pdfviewer_web: ^20.2.49-beta
  syncfusion_pdfviewer_windows: ^20.2.49-beta
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/resume.pdf
    - assets/sample.pdf